### ISSUE TITLE
Code generation failed

### ISSUE THREAD

**Issue by AtirChaudary** [OpenAADL/ocarina#101]
when i try to make files (the examples in the pok which have aadl files ) i get the following error 

Compile node cpu (generated-code/cpu)
make[6]: *** No rule to make target `clean'.  Stop.
make[5]: *** [clean] Error 2
make[4]: *** [clean] Error 2
make[3]: *** [clean] Error 2
make[2]: *** [kernel] Error 2
make[1]: *** [build-kernel] Error 2
Code generation failed
make: *** [build] Error 1

i am not understanding this i have re- downloaded the whole pok and reinstalled the ocarina 
still the same issue is there can you help on this ?

**Comment by yoogx** [comment]
From your answer on POK issue, it seems this issue is solved. Can you please confirm ?
Also, I would need more details if this is still an issue. Closing for the moment
