### ISSUE TITLE
pull requests-about the mechanism of Ocarina 

### ISSUE THREAD

**Issue by pioneerxian** [OpenAADL/ocarina#107]
DESCRIPTION:

Now I can use OSATE tools to generate C code based on the VxWorks653 System through adding the plugin Ocarina,But I don't understand the mechanism of Ocarina plugin. In simple terms, I don't know the code project in which each C file is on behalf of the meaning and the file name is how to produce.Here is for C code in the following comment .Please people who understand the knowledge of this to help solve the problem or provide some information about the Ocarina on code genearation, thank you very much

    SAMPLE FIX/WORKAROUND:
The framework of generated code:
activity.h
activity.c
deployment.h
deployment.c
gtypes.h
gtypes.c
marshallers.h
marshallers.c
naming.h
naming.c
request.h
request.c
subprograms.h
subprograms.c
main.c

**Comment by yoogx** [comment]
You may want to review the following videos regarding integration of Ocarina generated code and ARINC653 here: http://www.aadl.info/aadl/demo-arinc653/
