### ISSUE TITLE
sending partition output over the netowork

### ISSUE THREAD

**Issue by AtirChaudary** [OpenAADL/ocarina#122]
Using ocarina with POK OS on ubuntu 14.04
i have been successful while generating code with ocarina and running my examples of POK OS
but one issue is that in the model i mentioned the port to each process and ip to the processor but still the data send by my one partition is not coming on that port or ip can you tell me why ?

 Location : aadlstring applies to (processor, device);
  --  Processor IP address (BSD_Sockets specific)

  Port_Number : aadlinteger applies to (process, device);
  --  IP port number of a process (BSD_Sockets specific)

i have used this in my model and given ip and port.

**Comment by yoogx** [comment]
Without full model information, it is impossible to answer. Furthermore, POK has its own issue reporting info. Did you review the network demo ? It should provide an entry point for network configuration.
