### ISSUE TITLE
Compiling Ocarina from source fails at ocarina_cmd.adb:635:07: "Try_Help" is undefined

### ISSUE THREAD

**Issue by vedranMv** [OpenAADL/ocarina#126]
OCARINA VERSION: n/a
    HOST MACHINE and OPERATING SYSTEM: Ubuntu 16.04.3 LTS (kernel 4.4.0-101-generic) 64-bit
    COMPILER VERSION: GNATLS 4.9.3, gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)
    DESCRIPTION:
I went on to compile Ocarina from sources only to find the compilation being interrupted at ocarina_cmd.adb:635:07 with message ```"Try_Help" is undefined```. Error is repeatable on my platform. I'm using build_ocarina script as follows 

```./build_ocarina.sh --scenario=fresh-install --prefix=$PWD/../build_debug --enable-debug``` 
(and ```build_debug``` folder exists already - but empty)
note: building without ```--enable-debug``` flag results in same behavior

build_ocarina.sh version: 04251f3

SOLUTION: Probably not the best approach but I deleted the line 635 in ```ocarina/src/main/ocarina_cmd.adb``` containing ```Try_Help;``` I'm not familiar with ada but if I comment it compiler complains about spaces. After removing the line manually resume compilation by running 'make' from ocarina/ subfolder that was checked out by build_ocarina script.

**Comment by yoogx** [comment]
You need a more recent version of GNAT to compile, either GCC 6 or GNAT GPL 2017
