### ISSUE TITLE
long file names under cygwin

### ISSUE THREAD

**Issue by juli1** [OpenAADL/ocarina#15]
When using Ocarina under cygwin, I get an error when trying to use Ocarina when long file names.

See the example below
jdelange@RM-BLACKCHERRY /cygdrive/c/Users/jdelange/git/pok/examples/arinc653-blackboard
$ ocarina -aadlv2 -f -i model.aadl /cygdrive/c/Users/jdelange/git/pok/misc/aadl-library.aadl
Cannot find file /cygdrive/c/Users/jdelange/git/pok/misc/aadl-library.aadl

But if I copy the aadl-library.aadl file into the current directory and avoid the long path, it works.

**Comment by juli1** [comment]
ping on this one

**Comment by yoogx** [comment]
Now we build using MSYS, not clear this is still an issue
