### ISSUE TITLE
Exit if no root system present

### ISSUE THREAD

**Issue by yoogx** [OpenAADL/ocarina#224]
If no root system is found, Ocarina should exit immediately. Otherwise, an exception is raised.

**Comment by maxime-esa** [comment]
Thanks!

**Comment by maxime-esa** [comment]
However, it's a bit rude for the caller to exit the application like that. You should return No_System instead.

The calling side is already expecting this case:
```
   Ocarina.Options.Root_System_Name :=
        Get_String_Name ("taste_dataview.others");

      if DV_Root /= No_Node then
         System := Root_System (Instantiate_Model (Root => DV_Root));  -- Here you should not exit!
      end if;

      if No (System) then
         raise Data_View_Error with "Could not instantiate Data View";
      end if;
```

**Comment by yoogx** [comment]
The bug report asked to exit immediately ;-)

I adjusted the logic to either exit or return no_node

In your code above, check the return value of Instantiate_Model, we may return no_node, and thus the call to Root_System could raise an exception

**Comment by maxime-esa** [comment]
Alright, perfect now. Thanks!
