### ISSUE TITLE
User-specified case is not respected

### ISSUE THREAD

**Issue by maxime-esa** [OpenAADL/ocarina#225]
I am specifying a initialize entrypoint to a function in C like this:
```
thread implementation My_C_Function_Pulse.others
properties
   Initialize_Entrypoint_Source_Text => "init_HELLOWORLD";
``` 
The case of the function name is not respected and POHIC generates this:

```
extern void init_helloworld (void);
```

This is not right and results in link errors.

**Comment by yoogx** [comment]
Duplicate of #5 .. yep, that old

**Comment by maxime-esa** [comment]
Alright, let me know when you can fix it, in the meantime I used a workaround.
