### ISSUE TITLE
Does Ocarina code generation tool covers Blackboard and Semaphores ?

### ISSUE THREAD

**Issue by CaptainSeum** [OpenAADL/ocarina#237]
Hi,

I tried to build an example to test code generation capabilities regarding the annex Arinc653. It works well for pretty much everything, but it does not seems to pick up blackboards and semaphores. I followed the instructions described in the AADL annex Arinc653 to specify those component.

Does Ocarina covers those concepts ? is there a specific way to specify blackboards and semaphores for Ocarina to parse them ?

Thanks

**Comment by yoogx** [comment]
your model might be incomplete, a quick examination of Ocarina source code demonstrates we emit code for blackboards and semaphores

**Comment by CaptainSeum** [comment]
Ok, is there any model example that contains semaphores/blackboards that works with Ocarina ?

**Comment by yoogx** [comment]
ADIRU is using blackboard
POK may have old models with semaphores
