### ISSUE TITLE
can not configure

### ISSUE THREAD

**Issue by SancSib** [OpenAADL/ocarina#27]
Hi, 
I can not install the program. ./configuration does not work. I had already installed gnatgcc. In bin folder, there is just ocarina-config but I dont know how I can create configuration and make files. 

I just started to use ocarina. Thank you.

**Comment by yoogx** [comment]
./configuration does not exist, ./configure does. Please read this file for more details
https://github.com/OpenAADL/ocarina/blob/master/INSTALL

Binary snapshots of Ocarina are available on http://www.openaadl.org

**Comment by SancSib** [comment]
I had already read the install file. But when write ./configure , it turns
me error : there is no file configure . Also there is no make file in bin
folder.

On Friday, February 20, 2015, Jerome Hugues <notifications@github.com>
wrote:

> ./configuration does not exist, ./configure does. Please read this file
> for more details
> https://github.com/OpenAADL/ocarina/blob/master/INSTALL
>
> Binary snapshots of Ocarina are available on http://www.openaadl.org
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenAADL/ocarina/issues/27#issuecomment-75197043>.
>


-- 
Sibel

**Comment by yoogx** [comment]
As explained in the INSTALL file

"If you modify source files, build Ocarina after a checkout or make
distclean, or the directory hierarchy of the source files, you should
re-generate autoconf and automake files (configure, Makefile.in...);
to do this, from the main directory, run:

./support/reconfig"

So, to generate configure, run ./support/reconfig ..

**Comment by SancSib** [comment]
bash: ./support/reconfig: No such file or directory

I will take such an error.



2015-02-20 18:39 GMT+02:00 Jerome Hugues <notifications@github.com>:

> As explained in the INSTALL file
>
> "If you modify source files, build Ocarina after a checkout or make
> distclean, or the directory hierarchy of the source files, you should
> re-generate autoconf and automake files (configure, Makefile.in...);
> to do this, from the main directory, run:
>
> ./support/reconfig"
>
> So, to generate configure, run ./support/reconfig ..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenAADL/ocarina/issues/27#issuecomment-75269242>.
>



-- 
Sibel

**Comment by yoogx** [comment]
How did you checkout Ocarina? and from which directory are you executing this command?

**Comment by SancSib** [comment]
In the ocarina folder and also in bin folder. But it does not configure in
both of them.

sibel@sibel-VGN-NS21Z-S:~/Applications
*/ocarina-2.0w-suite-i686-pc-linux-gnu-2014121*8$ ./configure
bash: ./configure: No such file or directory
sibel@sibel-VGN-NS21Z-S:~/Applications
*/ocarina-2.0w-suite-i686-pc-linux-gnu-20141218/bin*$ ./configure
bash: ./configure: No such file or directory
sibel@sibel-VGN-NS21Z-S:~/Applications/
*ocarina-2.0w-suite-i686-pc-linux-gnu-20141218/bin*$ ./support/reconfig
bash: ./support/reconfig: No such file or directory

I also copy the bin file into the directory : /user/local/bin

sibel@sibel-VGN-NS21Z-S*:/usr/local/bin*$ ./configure
bash: ./configure: No such file or directory
sibel@sibel-VGN-NS21Z-S*:/usr/local/bin*$ ./support/reconfig
bash: ./support/reconfig: No such file or directory


On the other hand, when I check if the program installed or not and write
"ocarina --version "
 from home directory, I can get the version number of the ocarina.

2015-02-20 19:46 GMT+02:00 Jerome Hugues <notifications@github.com>:

> How did you checkout Ocarina? and from which directory are you executing
> this command?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenAADL/ocarina/issues/27#issuecomment-75285817>.
>



-- 
Sibel

**Comment by yoogx** [comment]
So you have the binary release of Ocarina, for which there is nothing do compile, simply use Ocarina as detailed in its User's Guide, visible here http://www.openaadl.org/doc/ocarina.html/

**Comment by SancSib** [comment]
If I understand your reply correctly, this means that the installation has
already been done. so there is no need to make configure. I think that I
can start to use ocarina for our models.

Thank you for your reply.

Best

2015-02-20 20:17 GMT+02:00 Jerome Hugues <notifications@github.com>:

> So you have the binary release of Ocarina, for which there is nothing do
> compile, simply use Ocarina as detailed in its User's Guide, visible here
> http://www.openaadl.org/doc/ocarina.html/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenAADL/ocarina/issues/27#issuecomment-75291266>.
>



-- 
Sibel

**Comment by yoogx** [comment]
Yes, you installed the binary release, meaning that all you have to do is run ocarina from the command line, or use the Eclipse integration plug-in

**Comment by SancSib** [comment]
Ok. thank you so much for your reply.

Best

2015-02-20 20:29 GMT+02:00 Jerome Hugues <notifications@github.com>:

> Yes, you installed the binary release, meaning that all you have to do is
> run ocarina from the command line, or use the Eclipse integration plug-in
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenAADL/ocarina/issues/27#issuecomment-75293235>.
>



-- 
Sibel
