### ISSUE TITLE
Python Binding Import Error

### ISSUE THREAD

**Issue by tkhamvilai** [OpenAADL/ocarina#280]
I follow Ocarina Python bindings from this document [https://readthedocs.org/projects/ocarina/downloads/pdf/latest/](url)
I can import most of the packages except "import libocarina_python"

I keep getting this error
`Traceback (most recent call last):
  File "<string>", line 1, in <module>`
`ImportError: /home/<my username>/Downloads/ocarina-build/ocarina_install/lib/libocarina-config.so: undefined symbol: __gnat_version
`

I have GNAT and gnatcoll installed. I think the issue comes from that the ocarina library cannot find these gnat libraries, but I couldn't solve it. Could you help me solve this issue?

Thank you in advance.

**Comment by yoogx** [comment]
The patch above should address this.
