### ISSUE TITLE
Issue when parsing records

### ISSUE THREAD

**Issue by juli1** [OpenAADL/ocarina#29]
When trying to parse the adiru model using the OSATE/Ocarina bridge, I got the following errors (see below). Seems that records are not parsed correctly.

/home/julien/local/bin/ocarina -k no-assert -k deos -aadlv2 -g pok_c -r adiru.deos -o /home/julien/git/AADLib/examples/adiru /home/julien/git/AADLib/examples/adiru/subprograms.aadl /home/julien/git/AADLib/src/property_set/pok.aadl /home/julien/git/AADLib/examples/adiru/partitions.aadl /home/julien/git/AADLib/examples/adiru/threads.aadl /home/julien/git/AADLib/examples/adiru/adiru_processor.aadl /home/julien/git/AADLib/examples/adiru/shm_datatype.aadl /home/julien/wip/runtime-osate/Plugin_Resources/Data_Model.aadl /home/julien/git/AADLib/examples/adiru/adiru_memory.aadl /home/julien/git/AADLib/examples/adiru/model.aadl /home/julien/wip/runtime-osate/Plugin_Resources/ARINC653.aadl
adiru_processor.aadl:61:04: parsing Boolean_Or_Record_Term, unexpected token '['
adiru_processor.aadl:61:27: parsing Property_Association or Contained_Property_Association, token ';' is expected, found identifier 'Description'
adiru_processor.aadl:60:02: parsing Component_Implementation, unexpected identifier 'ARINC653'
Cannot parse AADL specifications

**Comment by yoogx** [comment]
This should be now solved.
