### ISSUE TITLE
In Osate 2.8, I have configured the path of Ocarina bin ，Why is it still showing Path to Ocarina is not setup 

### ISSUE THREAD

**Issue by Lqs66** [OpenAADL/ocarina#291]
In Osate 2.8, I have configured the path of Ocarina bin ，Why is it still showing Path to Ocarina is not setup

**Comment by jjhugues** [comment]
I just confirmed it works in my setup. You should confirm you have proper permissions to the binary.

**Comment by Lqs66** [comment]
> I just confirmed it works in my setup. You should confirm you have proper permissions to the binary.

Sorry, my computer knowledge is very poor, can you go into more detail?

**Comment by jjhugues** [comment]
Depending on the OS you are using, check you have read/write permissions.
Also, clarify what you mean by "Path to Ocarina is not setup", is it in the preference pane or when running one of the Ocarina command?

**Comment by Lqs66** [comment]
> when running one of the Ocarina command

thank you for your reply ，when running one of the Ocarina command，"Path to Ocarina is not setup" was shown

**Comment by Lqs66** [comment]
> Depending on the OS you are using, check you have read/write permissions.
> Also, clarify what you mean by "Path to Ocarina is not setup", is it in the preference pane or when running one of the Ocarina command?
I have read/write permissions，but it doesn't work

**Comment by jjhugues** [comment]
Can you make a screenshot of the preference panel that shows the path? enlarge the window to show the full path

**Comment by Lqs66** [comment]
> Can you make a screenshot of the preference panel that shows the path? enlarge the window to show the full path

![image](https://user-images.githubusercontent.com/62269820/112163913-6d951780-8c28-11eb-852e-03c75f3f472b.png)

**Comment by Lqs66** [comment]
> Can you make a screenshot of the preference panel that shows the path? enlarge the window to show the full path

I have uploaded the picture, can you see it? Can you give me some suggestions?

**Comment by jjhugues** [comment]
As I said, it should work. Did you try running Ocarina from the command line? You used a very old version of Ocarina, I cannot guarantee it will run on your system

**Comment by Lqs66** [comment]
> You used the darwin version, which is meant for macOS
> but you PATH looks like a Windows one, so you should at least install the windows version

I found that this is indeed the case, where should I find the windows version ？

**Comment by yoogx** [comment]
There is no 2017.1 release version for Windows. I suggest you test on Linux and build it from source, this is fully documented in the ocarina-build repository.

Build for Windows are also supported, but not testeD.
