### ISSUE TITLE
ocarina version and AADL Doc version

### ISSUE THREAD

**Issue by ibertli** [OpenAADL/ocarina#311]
hello, sir! my ocarina version is :Ocarina v2017.1，but the newest AADL standard is AS5506D, which is published in 2022. so if i write a demo on AS5506D, how can i build it in ocarina?

**Comment by yoogx** [comment]
AS5506D is a minor update, your model is certainly valid. Just try

**Comment by ibertli** [comment]
> AS5506D is a minor update, your model is certainly valid. Just try

ok, thanks, i will try later!
