### ISSUE TITLE
about a trusted compiler

### ISSUE THREAD

**Issue by ibertli** [OpenAADL/ocarina#312]
hello, sir. Now we can generate a .c file from .aadl using ocarina, but i want to know how to prove the compiler is a trusted compiler? i mean like L2C project(https://github.com/l2ctsinghua/l2c), whether we can use some tools to prove that.
Looking forward to your reply!

**Comment by yoogx** [comment]
l2c is quite old. You may want to use this instead: https://github.com/INRIA/velus

Ocarina can generate SPARK2014 code, see https://www.sciencedirect.com/science/article/pii/S1383762121002599

This provides the foundation for assessing that the code is correct. Not that this is a trusted compiler though. 

Ocarina evolved into Oqarina; see https://github.com/Oqarina/oqarina
There is no support for code generation; this might happen in the future though

**Comment by ibertli** [comment]
> 

Thanks for your reply, i will look into your suggestion carefully.
