### ISSUE TITLE
whether a 'processor' can have a 'data port'?

### ISSUE THREAD

**Issue by ibertli** [OpenAADL/ocarina#317]
Hello Sir,
    I have encountered a problem and need your help.
    In page 97 on 'SAE AS 5506D-2022.pdf', in the processor's 'Legality Rules', i can define a processor with a data port feature, just like the example:
*************
processor p1
features
  p1: in data port Base_Types::integer;
end p1;
*************
What makes me confused is that 'processor' is a hardware component, how can define a port used to receive int data?  I want to confirm whether the above example is correct and i can describe a 'processor' like that?

Looking forward to your reply!

**Comment by jjhugues** [comment]
Please use AADL open forum for these questions

* [sae-aadl](https://lists.sei.cmu.edu/mailman/listinfo/sae-aadl) to discuss AADL standardization topics.
* [ sae-aadl-users](https://lists.sei.cmu.edu/mailman/listinfo/sae-aadl-users) to discuss AADL usage.
* [ OSATE Google group](https://groups.google.com/forum/#%21forum/osate) to discuss OSATE-related topics.
