### ISSUE TITLE
Clean command line flags

### ISSUE THREAD

**Issue by yoogx** [OpenAADL/ocarina#33]
A few flags should be obsoleted, like -c. This issue tracks improvements in this area

**Comment by pgaufillet** [comment]
It would be nice also to comply with [GNU coding standard regarding command line interfaces] (https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html).

**Comment by yoogx** [comment]
I opened issue #54 for the support of GNU standard
