### ISSUE TITLE
Fixing output file for cheddar generation does not work

### ISSUE THREAD

**Issue by Ellidiss** [OpenAADL/ocarina#34]
By launching the following command:"ocarina -aadlv2 -o ./truc.xml -g cheddar ../../sandbox/examples/deployment.aadl ../../sandbox/examples/rma.aadl"
the following error is raised: "Message: directory "./truc.xml" does not exist"
whereas -o shall point to the file where Ocarina is to generate cheddar xml file.

**Comment by yoogx** [comment]
Thanks. Note that there is a glitch in the documentation, -o is for specifying the output directory, not output file.
