### ISSUE TITLE
APPLIES TO (System implementation) raises error when used

### ISSUE THREAD

**Issue by Ellidiss** [OpenAADL/ocarina#35]
Lets have the following AADL declarations.

A AADL model.aadl:
> PACKAGE client_server_Pkg
> PUBLIC
> WITH AI;
> 
> SYSTEM client_server
> END client_server;
> 
> SYSTEM IMPLEMENTATION client_server.others
> PROPERTIES
>   AI::root_system => "SELECTED";
> END client_server.others;
> 
> END client_server_Pkg;

A property set p1.aadl:
> PROPERTY SET ai IS
> 
>   Root_System : AADLSTRING
>     APPLIES TO (SYSTEM);
> END ai;

A property set p2.aadl:
> PROPERTY SET ai IS
> 
>   Root_System : AADLSTRING
>     APPLIES TO (SYSTEM IMPLEMENTATION);
> END ai;

Instantiating model.aadl+p1.aadl in Ocarina works.
Instantiating model.aadl+p2.aadl in Ocarina raises the error: " AI  root_system cannot apply to client_server.others".

**Comment by yoogx** [comment]
Issue solved, test case now in regression test suite
