### ISSUE TITLE
Support of C++ as implementation language for AADL subprograms

### ISSUE THREAD

**Issue by Stachelbeck** [OpenAADL/ocarina#4]
I created a simple AADL v2.1 Rate Monitonic Scheduling single a single thread calling one subprogram. The subprogram is written in C++ (I all so developed a C version of the same subprogram). When staring ocarina to generate code I receive the following error message from ocarina:

IDAeNetBusManagera.aadl:7:30 Backends: fatal error : This kind of subprogram is not supported SUBPROGRAM_UNKNOWN

AADL v2.1 specification:

subprogram BCMgr
  properties
    Source_Language => (CPP);
    Source_Name => "bcmgr";
    Source_Text => ("bcmgr.cpp");
end BCMgr;

My ocarina verion is dated 12-17-2012. 

This is the C version in which ocaina will generate code and its generated and user created code (bcmgr.c) will compile and execute on the targeted machine.

subprogram BCMgr
  properties
    Source_Language => (C);
    Source_Name => "bcmgr";
    Source_Text => ("bcmgr.c");
end BCMgr;

Thanks,

Kenneth

**Comment by jenewari** [comment]
hello, i want to know how to use code generation in osate, where can i get something comprehensive to help me use osate

**Comment by yoogx** [comment]
Hi,

You may start with resources from http://www.openaadl.org/osate-ocarina.html
and the following examples: http://www.openaadl.org/aadlib.html

**Comment by jenewari** [comment]
thanks, but is there any other resources on how to use code generation?

**Comment by yoogx** [comment]
Using code generation is nothing more than pointing the root system to the tool, as detailed in the first link. Unless you have more precise question, I strongly suggest you try first. 

Also, please do not use old tickets to discuss unrelated issues.
