### ISSUE TITLE
compile error on ubuntu

### ISSUE THREAD

**Issue by hardfist** [OpenAADL/ocarina#57]
OS: Ubuntu 14.04.2 LTS \n \l
compiler: GNATMAKE 4.6
when I build ocarina from source I met the following error
```
gcc-4.6 -c -gnatec=/root/git/ocarina/src/../projects/restrictions.adc -O2 -fPIC -gnat12 -gnata -gnaty -gnatyu -gnatys -gnatpn -I- -gnatA /root/git/ocarina/src/core/model/ocarina-builder-aadl-components-prototypes.adb
ocarina-aadl_values.ads:68:26: missing operand
gnatmake: "/root/git/ocarina/src/core/model/ocarina-analyzer-aadl-finder.adb" compilation error
make[1]: *** [ocarina-core.gpr-build] Error 4
make[1]: Leaving directory `/root/git/ocarina/projects'
make: *** [all-recursive] Error 1
```

**Comment by yoogx** [comment]
GCC 4.6 is too old, check the build requirements from the Ocarina documentation:
http://ocarina.readthedocs.org/en/latest/installation.html#build-requirements

Note I'm updating Ocarina to use some Ada 2012 features, so using GNAT GPL 2015 or GCC 5.1 is highly recommended
