### ISSUE TITLE
Error Compiling on Mac

### ISSUE THREAD

**Issue by kjherring** [OpenAADL/ocarina#60]
I received the following when compiling on Mac (OSX:Yosemite, GNAT GPL 2014, Xcode 7.0.0.72)

ambiguous instructions require an explicit suffix (could be 'filds', or 'fildl')
        fild    -322(%rbp)
        ^
ambiguous instructions require an explicit suffix (could be 'fisttps', or 'fisttpl')
        fisttp  -322(%rbp)
        ^
ambiguous instructions require an explicit suffix (could be 'filds', or 'fildl')
        fild    -322(%rbp)

any known fixes?

**Comment by yoogx** [comment]
Check this bug report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66509

Solution is to install a newer GCC, I got success with GCC 5.2.0 from this link: https://groups.google.com/forum/m/#!topic/comp.lang.ada/HaP0_jsxnng
