### ISSUE TITLE
dependecy on libwinpthread-1.dll

### ISSUE THREAD

**Issue by juli1** [OpenAADL/ocarina#69]
Hello,

When trying to use the latest windows build, I got the following issue (see screenshot). Is there any additional required dependency to install to get it working?

Thanks.
![winpthread-dependency](https://cloud.githubusercontent.com/assets/993972/17217891/f99f3b22-54b3-11e6-9764-3cb8e57759ef.PNG)

**Comment by yoogx** [comment]
Probably a misconfiguration on my end, I may have compiled for cygwin, and so you miss this dependency. Furthermore, this binary is ad hoc and quite old. I'll see if I can generate a new one.

**Comment by yoogx** [comment]
Indeed, I got issues using the "wrong" compiler for Windows. I updated build requirements for Windows in commit cf90f20eb2931285082fe2a5e1c7292e040c35cf 

I also pushed a new tarball for testing. Please test and report
