### ISSUE TITLE
Errore in the python code

### ISSUE THREAD

**Issue by Hi-Zed** [OpenAADL/ocarina#85]
There is an error in:
`/resources/runtime/python/ocarina/ocarina.py` at line 137.

Currently it's:
`return runOcarinaFunction (libocarina_python.getSourcePorts, nodeId)`
Should be:
`return runOcarinaFunction (libocarina_python.getSourcePorts, feature_nodeId)`

**Comment by yoogx** [comment]
Thanks for the report, this is now solved
